### ISSUE TITLE
Problems accessing certain files with fs-gcsfs while it works with plain gcsfs

### ISSUE THREAD

**Issue by leberknecht** [Othoz/gcsfs#18]
Hi!
I have some problems accessing certain files using `fs_gcsfs`. Im struggling with figuring out what exactly the problem is, as it does not affect all files. Accessing the files directly through `gcsfs` works though.
```python
>>> import gcsfs
>>> t = gcsfs.GCSFileSystem(project='some-company')
>>> p = t.open('gs://my-bucket/my-folder/README.md')
>>> p
<File-like object GCSFileSystem, my-bucket/my-folder/README.md>
>>>
>>> from fs import open_fs
>>> t = open_fs('gs://my-bucket/')
>>> t.open('my-folder/README.md')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/fs/base.py", line 1166, in open
    bin_file = self.openbin(path, mode=bin_mode, buffering=buffering)
  File "/usr/local/lib/python3.7/site-packages/fs_gcsfs/_gcsfs.py", line 348, in openbin
    info = self.getinfo(path)
  File "/usr/local/lib/python3.7/site-packages/fs_gcsfs/_gcsfs.py", line 127, in getinfo
    raise errors.ResourceNotFound(path)
fs.errors.ResourceNotFound: resource 'my-folder/README.md' not found
>>> t.exists('my-folder/README.md')
True
>>> t.open('other-folder/some-file.csv')
    <_io.TextIOWrapper name='other-folder/some-file.csv' encoding='utf-8'>
```
So for some reason i can access `other-folder/some-file.csv` but not `my-folder/README.md` when using `fs_gcsfs`. From what i see, the acl and iam for both files look pretty much the same:
```bash
% gsutil acl get gs://my-bucket/my-folder/README.md
[
  {
    "entity": "project-owners-605693490522",
    "projectTeam": {
      "projectNumber": "605693490522",
      "team": "owners"
    },
    "role": "OWNER"
  },
  {
    "entity": "project-editors-605693490522",
    "projectTeam": {
      "projectNumber": "605693490522",
      "team": "editors"
    },
    "role": "OWNER"
  },
  {
    "entity": "project-viewers-605693490522",
    "projectTeam": {
      "projectNumber": "605693490522",
      "team": "viewers"
    },
    "role": "READER"
  },
  {
    "email": "some-service-account@some-company.iam.gserviceaccount.com",
    "entity": "user-some-service-account@some-company.iam.gserviceaccount.com",
    "role": "OWNER"
  }
]
% gsutil iam get gs://my-bucket/my-folder/README.md
{
  "bindings": [
    {
      "members": [
        "projectViewer:some-company"
      ], 
      "role": "roles/storage.legacyObjectReader"
    }, 
    {
      "members": [
        "projectOwner:some-company", 
        "projectEditor:some-company", 
        "serviceAccount:some-service-account@some-company.iam.gserviceaccount.com"
      ], 
      "role": "roles/storage.legacyObjectOwner"
    }
  ], 
  "etag": "CAE="
}

% gsutil acl get gs://my-bucket/other-folder/some-file.csv
[
  {
    "email": "some-service-account@some-company.iam.gserviceaccount.com",
    "entity": "user-some-service-account@some-company.iam.gserviceaccount.com",
    "role": "OWNER"
  },
  {
    "entity": "project-owners-605693490522",
    "projectTeam": {
      "projectNumber": "605693490522",
      "team": "owners"
    },
    "role": "OWNER"
  },
  {
    "entity": "project-editors-605693490522",
    "projectTeam": {
      "projectNumber": "605693490522",
      "team": "editors"
    },
    "role": "OWNER"
  },
  {
    "entity": "project-viewers-605693490522",
    "projectTeam": {
      "projectNumber": "605693490522",
      "team": "viewers"
    },
    "role": "READER"
  }
]
% gsutil iam get gs://my-bucket/other-folder/some-file.csv
{
  "bindings": [
    {
      "members": [
        "serviceAccount:some-service-account@some-company.iam.gserviceaccount.com",
        "projectOwner:some-company",
        "projectEditor:some-company"
      ],
      "role": "roles/storage.legacyObjectOwner"
    },
    {
      "members": [
        "projectViewer:some-company"
      ],
      "role": "roles/storage.legacyObjectReader"
    }
  ],
  "etag": "CAE="
}
```
The `GOOGLE_APPLICATION_CREDENTIALS` env-variable is set to a service-account file for `some-service-account`.
Any idea how i can debug/solve this? Using 
```
fs-gcsfs                   1.0.0    
gcsfs                      0.3.0 
```

**Comment by trendelkampschroer** [comment]
I can't debug this at the moment. But it seems that fs.open guesses the file type (text or binary) from the file-ending and tries to open the .md file as a binary raising an Exception.

I would try to see how this guess is implemented in fs.open, maybe it will becone clear then.

**Comment by mathiaseitz** [comment]
Hi,

one additional idea on how to debug / solve this: it might be possible that you are running into https://fs-gcsfs.readthedocs.io/en/latest/#limitations, especially if the "folder structure" in your bucket has been created before using fs_gcsfs.
Could you double check if the "marker blobs" aka directories exist for the files that are giving you exceptions? If you are allowed to modify the bucket, you could you could also let fs_gcsfs create those for you, see https://fs-gcsfs.readthedocs.io/en/latest/#fs_gcsfs.GCSFS.fix_storage.

**Comment by leberknecht** [comment]
Indeed! Running `fix_storage` did solve the problem!
Thanks a lot!
